Jigsaw-Code/outline-go-tun2socks

android/common.go, android/intra.go, android/outline.go, go.mod, go.sum, tun2socks/common.go, tun2socks/intra.go, tun2socks/intra/tcp.go, tun2socks/intra/udp.go, tun2socks/outline.go
This includes a refactor to share code between Intra and Outline.
Note: This changes the name `AndroidTunnel` to `OutlineTunnel`, requiring a corresponding change in cordova-plugin-outline.
=> Add an Intra-style tunnel for Android

Makefile, android/common.go, android/intra.go, android/outline.go, apple/tun2socks.go, tunnel/common.go, tunnel/intra.go, tunnel/intra/tcp.go, tunnel/intra/udp.go, tunnel/outline.go
These metrics are chosen to match Intra's current
set of socket metrics (except for retry-related
metrics, since retry is not yet implemented in
this Handler).
Notably, this change renames one of the two tun2socks
packages (renamed to "tunnel"), and exposes bindings for
additional packages.  This appears to be necessary
because gobind can only expose types from packages that
are explicitly exported.
=> Expose a summary of socket activity for Intra

tunnel/intra/retrier.go, tunnel/intra/retrier_test.go, tunnel/intra/tcp.go, tunnel/intra/udp.go
This change introduces a split-retry pseudo-Dialer, which is used for TCP port 443.  It should match Intra's current retry behavior reasonably precisely.
=> Implement split-retry logic

Makefile, build_android.sh
* Passes the `-work` flag to `gomobile bind` in order to get Go's working directory and copy JNI binaries.
* Stops stripping debug symbols in Android builds to enable crash reporting tools to extract them.
=> Android: retrieve JNI binaries, don't strip debug symbols

tunnel/intra/retrier.go, tunnel/intra/retrier_test.go
Previously, retrier.conn would become nil if DialTCP
failed in the retry.  This would lead to a null pointer
exception at CloseRead().
=> Ensure that retrier.conn is never nil

android/common.go, tunnel/outline.go
* Increases garbage collection frequency in order to reduce Android memory usage.
* Profiled memory usage in the Outline client app before and after the change. Observed a ~9% memory usage reduction under active network conditions.
Before
After
=> Android: increase garbage collection frequency

tunnel/intra/retrier.go, tunnel/intra/retrier_test.go
This bug was causing all connections to be killed once they
went idle.
=> Unset deadline after handshake completes

tunnel/intra/tcp.go
This reverts commit c13d6d53cfba1c8a8d017bb401eddd48658f5028.
It turns out that go-tun2socks doesn't wait for Handle() to
return before returning success from tcpAcceptFn, so delaying
the return does not have the intended effect.
=> Revert "Delay RST caused by Network Unreachable"

Makefile, README.md, build_macos.sh
* Fixes the macOS build from changes in #22.
* Apple runtime patches are no longer necessary in Go 1.13. Updates the README and deletes the custom Go runtime.
* Commits gomobile with macOS framework support built with Go 1.13.
* Removes unused variables from the Makefile.
=> Build system improvements

outline/android/tun2socks.go, outline/shadowsocks/connectivity.go, shadowsocks/tcp.go, shadowsocks/udp.go, tunnel/outline.go, tunnel/tunnel.go
* Implements (go-tun2socks) Shadowsocks connection handlers.
* Replaces Outline's SOCKS tunnel with a Shadowsocks tunnel.
* Updates the `OutlineTunnel` interface to support network connectivity change notifications.
* Fixes a TUN file descriptor ownership contract violation by not closing the TUN writer on tunnel disconnect, which in Android closes the underlying file descriptor.
=> Outline Shadowsocks tunnel

tunnel/intra/direct_split.go, tunnel/intra/retrier.go, tunnel/intra/retrier_test.go, tunnel/intra/tcp.go
This is a prerequisite for DoH to use the retrier.
This change also adds a configurable TCP handshake
timeout to retrier, and simplifies the direct split code.
=> Make DuplexConn a net.Conn

intra/intra.go, tunnel/intra.go, tunnel/intra/tcp.go
We need DOH in the constructor to ensure correct handling
of the initial packets that are read from the tun device.
This change also enables asynchronous control of `alwaysSplitHTTPS`,
which is preferable because it may take several seconds to
determine whether this setting should be enabled.
=> Add DOH to the Intra tunnel constructor

tunnel/intra/doh/doh.go, tunnel/intra/doh/doh_test.go, tunnel/intra/doh/ipmap/ipmap.go, tunnel/intra/doh/ipmap/ipmap_test.go
With this change, server IPs will be disconfirmed if
they are reachable but not correctly functioning,
and sockets will be closed if they start reporting
errors.
This change also adds significantly more debug logging,
which is not enabled in the default build.
=> Drop server IPs and sockets that aren't working

tunnel/intra/doh/doh_test.go
2d8ca51e12d950199239a6afe5f6f45daf27bf62 changed the Listener interface by removing `OnTransaction` and adding `OnQuery` and `OnResponse`, but it looks like the `fakeListener` implementation got left behind.
=> Update fakeListener to support new Listener interface

tunnel/intra/doh/doh.go
The tests use this behavior for the sake of compactness.
=> Accept nil dialer in doh.NewTransport

tunnel/intra/doh/ipmap/ipmap.go, tunnel/intra/protect/protect.go, tunnel/intra/protect/protect_test.go
Go on Android cannot determine the system's preferred DNS servers.
This is normally fine, because Resolver.PreferGo defaults to false,
but we need to set PreferGo to true when protection is enabled,
in order to protect the DNS query's UDP socket.
This change requires a Protector to indicate the list of DNS
servers, so that the Resolver can create a protected socket to
one of those servers.
=> Improve protection of DNS queries

tunnel/intra/protect/protect.go
This happens frequently on Kitkat (Android 4.4).
A panic might be appropriate if protect _always_ fails,
because the whole system will be nonfunctional, but
for sporadic or edge-case failures it's ok to log
the error and continue.
=> Don't panic if protect() returns false

go.mod, go.sum, tunnel/intra/tcp.go
This code was attempting to send the Choir report too early, before the
SNI would have been transmitted.
=> Update Choir and fix Choir reporting

go.mod, intra/intra.go, outline/android/tun2socks.go, outline/electron/main.go, tunnel/intra.go, tunnel/outline.go, tunnel/tun.go, tunnel/tunnel.go
os.NewFile takes ownership of the file descriptor, and adds a finalizer
that closes the file descriptor when the file is garbage-collected.
This violates Outline's interface contract (caller retains ownership of
the TUN device), and could cause a problem if the file descriptor is
still being used
See https://github.com/Jigsaw-Code/Intra/issues/285
=> Don't use os.NewFile to create the TUN writer

intra/tunnel.go
A significant amount of UDP connections on Android are DNS requests.
An hour long timeout for them isn't really helpful especially considering DNS
TTLs themselves are considerably shorter. Besides, RFC 4787 recommends
at least a timeout of 5mins, which is still high for DNS, but may work nicely for
other UDP connections, at least according to the RFC.
#72
=> Set Intra UDP NAT timeout to 5 minutes

https/fetch.go, https/fetch_test.go
- Exposes a method to fetch HTTPs data with support for (self-signed) certificate pinning and HTTP redirects.
- Needed to support SIP008 Online Config in the Outline clients.
- Note that this is not yet exposed to the gomobile libraries. I indend to expose it in `outline/https`, with a string-based API (required for Cordova) and Outline error codes.
- Replaces and incorporates review comments from #76.
=> Fetch HTTPs

outline/android/tun2socks.go, outline/apple/tun2socks.go, outline/electron/main.go, outline/tunnel.go, shadowsocks/tcp.go, shadowsocks/udp.go
This change moves Shadowsocks client setup to the caller, which avoids passing a large number of arguments across several packages and enables more flexibility for changes to the Shadowsocks client configuration (starting with #95).
=> cleanup: Refactor tunnel creation function arguments

Makefile
This is necessary for gomobile to find the gobind binary on my Mac.
=> fix(apple, build): Add path extension to gomobile invocation

outline/android/tun2socks.go, outline/apple/tun2socks.go, outline/electron/main.go, outline/shadowsocks/config.go, outline/shadowsocks/connectivity.go
This ensures that the connectivity checks more accurately match real connections to that server.
=> Use the specified prefix for the connectivity checks

outline/shadowsocks/connectivity.go, shadowsocks/connectivity.go
This change adjusts the connectivity check to fix two issues reported by users:
1. On low-quality networks, the test sometimes fails even though the server is reachable.  This is addressed by lengthening the timeouts.
2. On networks that are blocking TCP access to the server, the test will succeed if UDP access is working, even though the server is effectively unusable.
This change has the negative effect of slowing down the connectivity check for all users.  If the server is working, the user must wait longer because both the UDP and TCP tests must complete, and the TCP test is slower than the UDP test.  If the server is unreachable, the test will wait for twice as long (10 seconds) before failing.
=> fix: adjust connectivity check heuristics

Makefile
There are three main changes here:
1. Add the Mac Catalyst platform to the Apple target.
2. Add quotes around variables that might contain spaces and get passed to the shell.
3. Pre-create the build directories for Linux and Windows.  (Otherwise, these directories are created on-demand by the xgo Docker image, which results in them being owned by root and read-only to the user.)
=> fix(build): Makefile maintenance

.github/workflows/build_and_test.yml, Makefile
Currently, `make linux` and `make windows` download and build the `master` branch, ignoring any changes in the local repository.  This change makes these commands build the local repository instead.
=> fix(build/electron): build the current branch

intra/doh/ipmap/ipmap_test.go
"example" was being resolved in my machine due to domain search, causing the tests to fail.
This change makes sure we use a root domain that doesn't exist.
=> refactor: fix Intra tests

outline/electron/main.go, outline/shadowsocks/client.go
Outline Client is referencing the following APIs (Android JNI interface as an example) exported by `gomobile`.
But due to the recent refactoring, we introduced types that are not recognized by `gomobile`. This is the only function exported in `master` branch now:
In this PR, I re-exported these functions (together with the new `NewClientFromJSON`) by using the built-in types. Here is the exported Android JNI interface:
/cc @sbruens , although the required APIs are re-exported, some of the data types still need to be updated:
* [`OutlineTunnel`](https://github.com/Jigsaw-Code/outline-client/blob/master/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnel.java#L49) -> `Tunnel`
* [`Tun2socksOutlineTunnel`](https://github.com/Jigsaw-Code/outline-client/blob/mas …
=> fix: 💊 re-export APIs used by Outline Client
